In [2]:
import pandas as pd

audience_df = pd.read_excel('test_data.xlsx', sheet_name='Данные об аудитории')
audience_df.head()

        date                               user_id  view_adverts
0 2023-11-11  8c020470-8461-11ed-83d0-552e8cc749d6            13
1 2023-11-18  5875f070-7b92-11ee-a6fb-8b298e83f4f7            14
2 2023-11-29  3c2d27c0-4fd6-11eb-b89f-2ffb31b67dd6            21
3 2023-11-29  234a96d0-ad16-11ed-a2e6-793ddfeeba1f            23
4 2023-11-29  4d07c180-644f-11eb-879c-b7c02edf4f37            12

In [3]:
mau = audience_df['user_id'].nunique()
print("MAU продукта равен:", mau)

MAU продукта равен: 7639

In [4]:
dau_by_day = audience_df.groupby('date')['user_id'].nunique()

mean_dau = dau_by_day.mean()
print("Средний DAU продукта равен:", mean_dau)

Средний DAU продукта равен: 560.4666666666667

In [5]:
audience_df['date'].dtype

dtype('<M8[ns]')

In [6]:
users_nov1 = audience_df[audience_df['date'] == '2023-11-01']['user_id'].unique()

users_nov2 = audience_df[audience_df['date'] == '2023-11-02']['user_id'].unique()

returned = len(set(users_nov1).intersection(set(users_nov2)))

retention_1d = (returned / len(users_nov1)) * 100

print(f"Пользователей 1 ноября: {len(users_nov1)}")
print(f"Вернулись 2 ноября: {returned}")
print(f"Retention 1-го дня: {retention_1d:.1f}%")

Пользователей 1 ноября: 623
Вернулись 2 ноября: 166
Retention 1-го дня: 26.6%

In [7]:
users_with_views = audience_df[audience_df['view_adverts'] > 0]

unique_users_with_views = users_with_views['user_id'].nunique()

conversion = (unique_users_with_views / 7639) * 100

print(f"Посмотрели объявления: {unique_users_with_views} пользователей")
print(f"Конверсия: {conversion:.1f}%")

Посмотрели объявления: 3538 пользователей
Конверсия: 46.3%

In [8]:
views_per_user = audience_df.groupby('user_id')['view_adverts'].sum()

mean_views = views_per_user.mean()

print(f"Среднее количество просмотров на пользователя: {mean_views:.1f}")

Среднее количество просмотров на пользователя: 2.9

In [11]:
ab_df = pd.read_excel('test_data.xlsx', sheet_name='Данные АБ тестов')
ab_df.head()

   experiment_num experiment_group   user_id  revenue
0               1             test     38456      520
1               1          control  13125924      806
2               1          control   9761984        0
3               1             test  11387012      208
4               1             test  18319648      104

In [15]:
import scipy.stats as stats

for i in[1, 2, 3]:

    exp_data = ab_df[ab_df['experiment_num'] == i]

    control_rev = exp_data[exp_data['experiment_group'] == 'control']['revenue']
    test_rev = exp_data[exp_data['experiment_group'] == 'test']['revenue']
    
    arpu_control = control_rev.mean()
    arpu_test = test_rev.mean()
    
    t_stat, p_val = stats.ttest_ind(control_rev, test_rev, equal_var=False)
    
    print(f"--- Эксперимент №{i} ---")
    print(f"ARPU Контроль: {arpu_control:.2f} | ARPU Тест: {arpu_test:.2f}")
    print(f"p-value: {p_val:.5f}")
    if p_val < 0.05:
        print("Результат: СТАТИСТИЧЕСКИ ЗНАЧИМ! (Есть реальная разница)\n")
    else:
        print("Результат: Незначим (Разница случайна)\n")

--- Эксперимент №1 ---
ARPU Контроль: 722.46 | ARPU Тест: 665.74
p-value: 0.68897
Результат: Незначим (Разница случайна)

--- Эксперимент №2 ---
ARPU Контроль: 704.65 | ARPU Тест: 332.93
p-value: 0.00113
Результат: СТАТИСТИЧЕСКИ ЗНАЧИМ! (Есть реальная разница)

--- Эксперимент №3 ---
ARPU Контроль: 663.21 | ARPU Тест: 998.67
p-value: 0.06032
Результат: Незначим (Разница случайна)

In [16]:
listers_df = pd.read_excel('test_data.xlsx', sheet_name='Листеры')

listers_df.head()

   user_id       date  cnt_adverts  age  cnt_contacts  revenue
0      100 2022-01-01            6   21           119       53
1      100 2022-01-02            2   21           200       18
2      100 2022-01-03            6   21           193       42
3      100 2022-01-04            2   21           143       38
4      100 2022-01-05            2   21           190       40

In [17]:
revenue_per_user = listers_df.groupby('user_id')['revenue'].sum()

print("Средний доход на пользователя:", revenue_per_user.mean())

Средний доход на пользователя: 156.48387096774192

In [18]:
unique_users_age = listers_df.groupby('user_id')['age'].first()

print("Медиана возраста пользователя:", unique_users_age.median())

Медиана возраста пользователя: 28.0